# Generated by Django 5.1.7 on 2025-03-23 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20190703_1816'),
    ]

    operations = [
        migrations.AddField(
            model_name='time',
            name='image',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
